config/routes.rb
Cardme::Application.routes.draw do
  root "welcome#index"

  resources :users do
    resources :cards, shallow: true 
    resources :groups
    resources :connections
  end

  resources :cards, only: [:index]


  get "/users/:user_id/connections/:id/cards", to: "cards#allcards"

 get "/groupsconnections", to: "groups_connections#index"

  post "/users/:id", to: "users#send_mail"
  post "/users/:id/sms", to: "users#send_sms"

  get "/invite", to: "invites#show"

  post "/invitesession", to: "session#newsession" 

  post "/joinfrominvite", to: "invites#create"

  #get "/allcards", to: "cards#allcards"

  get "/connections", to: "connections#index"
  get "/connections/:id/groupsconnections", to: "groups_connections#index"
  post "/connections", to: "connections#create"
  delete "/connections/:id", to: "connections#destroy"

  post "/groupsconnections", to: "groups_connections#create"
  delete "/groupsconnections", to: "groups_connections#destroy"

  # get "/groupsconnections", to: "groups_connections#index"

  #get "/groupsconnections", to: "groups_connections#index"
  #get "connections/:id/groupsconnections", to: "groups_connections#index"


  get "/login", to: "session#new"
  post "/session", to: "session#create"
  delete "/logout", to: "session#destroy"

  get "/card_dashboard/:id", to: "cards#card_dashboard"
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :cards
  has_many :groups
  has_many :connections

  validates :email, presence: true
  has_secure_password

  def send_text(user, phone, token)
    @token = token
    @user = user
    @phone = phone
    @twilio_client = Twilio::REST::Client.new ENV["TWIL_SID"], ENV["TWIL_AUTH"]
    @twilio_client.account.sms.messages.create(
      :from => "+17472013048",
      :to => "+1#{@phone}",
      :body => "#{@user.first_name} has sent you a cardMe, Click link to view: http://localhost:3000/invite?=#{@token.secret_key}"
      )
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user, only: [:show, :edit, :update, :destroy, :send_mail, :send_sms]
  before_action :authenticate, :authorize, only: [:edit, :update, :show]
  
  def send_mail
    @email = params[:email]
    @card = Card.find_by(card_name: params[:my_cards])
    @token = Token.new(card: @card)
    @token.generateKey
    @token.save

    # # user1 card1 -> user2
    # # check in connections that ! user2 card1

    # reciever = User.find_by(email: @email)
    # reciever_connections = reciever.connections.map(&:user_id)

    # if(reciever_connections.include?(@card.id)) 
    #   flash[:notice] = "Already connected! Visit your Rolodex!"
    # else 
      if UserMailer.send_card(@user, @token, @email).deliver
        flash[:notice] = 'Card Sent!'
      else
        flash[:notice] = "Problems sending mail - please double check the address"
      end
    # end

      redirect_to user_path
  end

  def send_sms
    @phone = params[:phone]
    @card = Card.find_by(card_name: params[:my_cards])
    @token = Token.new(card: @card)
    @token.generateKey
    @token.save

    # reciever = @user.cards.find_by(phone_number: @phone)
    # reciever_connections = reciever.connections.map(&:user_id)

    # if(reciever_connections.include?(@card.id)) 
    #   flash[:notice] = "Already connected! Visit your Rolodex!"
    # else 
      if @user.send_text(@user, @phone, @token)
        flash[:text_notice] = 'Text Sent!'
      else
        flash[:text_notice] = 'Problems sending text - please double check the phone number'
      end
    # end

    redirect_to user_path
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if  @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def show
    @cards = @user.cards.all
    @card = Card.find_by(card_name: params[:card_name])
    @my_card = @cards.map(&:card_name)
  end

  def edit
    @update_worked = true
  end

  def update
    @update_worked = @user.update(user_params)

    if @update_worked
      redirect_to user_path(@user)
    else
      render(:edit)
    end
  end

  def load_user
    return @user = User.find(params[:id])
  end 

  def authenticate
    unless logged_in?
      redirect_to root_path
    end
  end

  def authorize
    unless current_user == @user
      redirect_to root_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :first_name, :last_name, :password, :password_confirmation)
  end

end

app/views/users/_form.html.erb
<div class = "form" >
  
    <% if @user.id.nil? %>
        <h2>JOIN US</h2>
    <% else %>
        <h2>EDIT PROFILE</h2>
    <% end %>
  <hr>

  <%= form_for @user do |f| %>
    <%= f.label :email %>
    <%= f.email_field :email %>
    <br/>

    <%= f.label :password %>
    <%= f.password_field :password %>
    <br/>

    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
    <br/>

    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
    <br/>

    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
    <br/>

    <%= f.submit @user.id.nil? ? "Join" : "Save Changes" %>
  <% end %>

</div>

app/views/users/edit.html.erb
Edit Profile
<%= render "form" %>

app/views/users/new.html.erb
<%= render "form" %>

app/views/users/show.html.erb
<div class="welcomepage">
  <p>Hello, <%= @user.first_name %>!<p>
  <%= link_to "Edit Profile", edit_user_path(@user) %>

<h2> SEND CARD </h2>
<hr>
<div class ="sendform">
  <div class ="text">
    <%= form_tag("/users/#{@user.id}/sms") do %>
      Phone Number: <%= text_field_tag 'phone' %>
      <%= label_tag("Select Card") %>
      <%= select_tag(:my_cards, options_for_select(@my_card)) %>
      <%= submit_tag "Text Card", class: 'button' %>
    <% end %>
  </div>

  <div class ="email">
    <%= form_tag(user_path(@user)) do %>
      Email: <%= email_field_tag 'email' %>
      <%= label_tag("Select Card") %>
      <%= select_tag(:my_cards, options_for_select(@my_card)) %>
      <%= submit_tag "Email Card", class: 'button' %>
    <% end %>
  </div>

  <div class="flash-message">
  <%= raw("<p><strong class='success'>#{flash[:notice]}</strong></p>") unless flash[:notice].nil? %>
  </div>
  <div class="flash-message">
  <%= raw("<p><strong class='success'>#{flash[:text_notice]}</strong></p>") unless flash[:text_notice].nil? %>
  </div>

<%= link_to "View My Rolodex", user_cards_path(@user) %>
</div>


<h2> MY CARDS </h2>
<hr>
<% if @cards.empty? %>
<%= link_to("Create a new card", new_user_card_path(@user)) %>
<% else %>
  <% @cards.each do |card| %>

    <div id="<%= card.id %>" class="card" style="background-image: url('<%= card.background_image %>'); background-size: 100%";>
      <div class="personal_info_list_wrapper">
        <div class="actual_list">
          <ul>
            <h4>Email Address</h4>
            <li><%= card.email %></li>
            <h4>Phone Number</h4>
            <li><%= card.phone_number %></li>
            <h4>Organization</h4>
            <li><%= card.organization %></li>
            <h4>Position</h4>
            <li><%= card.position %></li>
          </ul>
        </div>
      </div>
            <div class="card-profile-pic" style="background-image: url('<%= card.profile_picture %>'); background-size: 100% 100%; height: 90px; width: 75px">
      </div>
    </div>
    <ul class="edit">
        <li><%= link_to("Edit", edit_card_path(card)) %></li>

       <li><%= form_tag card_path(card), method: "delete", data: {confirm: "Are you sure you want to delete this card?"} do %>
       <%= submit_tag("Delete") %>
       <% end %> </li>
    </ul>
    <% end %>
    <br>
    <div class="create-card">
    <%= link_to("Create Another Card", new_user_card_path(@user)) %>
    </div>
  <% end %>

</div>